# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Baisibudejie' do

 pod 'AFNetworking', '~> 3.2.1'
 pod 'MJExtension', '~> 3.0.15.1'
 pod 'SDWebImage', '~> 5.0.0-beta'
 pod 'SVProgressHUD', '~> 2.2.5'
end
